{% set name = "jupyterlab-recents" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3b48727350cf8bdf063c29fd6184761007bca7ec1d0adfae87bb378f7e1ecf54

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - jupyter-packaging >=0.7.9,<0.8.0
  run:
    - python >=3.7

test:
  requires:
    - jupyterlab >=3.0.0,<4.0.0
  commands:
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-recents.*OK"
    - python -m jupyterlab.browser_check  # [not linux]

about:
  home: https://github.com/NERSC/jupyterlab-recents
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab extension that tracks recent files and directories.

extra:
  recipe-maintainers:
    - fcollonval
